### ISSUE TITLE
Export fails with ValueError

### ISSUE THREAD

**Issue by jensens** [plone/plone.distribution#86]
with 2.0.0a1
```shell
(.venv) ~/ws/pro/customer/myproject/backend (main✔)$ export-distribution instance/etc/zope.conf Plone
Exporting Plone site at /Plone
 Target path: /home/jensens/ws/pro/customer/myproject/backend/src/myproject/backend/distributions/customer/content
Traceback (most recent call last):
  File "/home/jensens/ws/pro/customer/myproject/backend/.venv/bin/export-distribution", line 8, in <module>
    sys.exit(export())
             ^^^^^^^^
  File "/home/jensens/ws/pro/customer/myproject/backend/.venv/lib/python3.12/site-packages/plone/distribution/cli/__init__.py", line 46, in export
    logger.info(f" Wrote {item.relative_to(path)}")
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensens/.pyenv/versions/3.12.2/lib/python3.12/pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: '/tmp/plone.exportimport8riir05a/content/__metadata__.json' is not in the subpath of '/home/jensens/ws/pro/customer/myproject/backend/src/myproject/backend/distributions/customer/content'
```

**Comment by ericof** [comment]
@jensens  Did you get any other error before?

**Comment by jensens** [comment]
I can not reproduce the error. I close this.
